# Project information
site_name: "Introduction to human PopGen"
site_author: Vladimir Bajić


# Theme
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - bash
        - R

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

# Pages  
nav:
    - Home:                     index.md
    - Background:               01_background.md
    - Exercise dataset:         02_data.md
    - Plink:                    03_plink.md
    - PCA:                      04_PCA.md
    - fastStructure:            05_fastStructure.md
    - Reference:                06_reference.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js